[theme]
primaryColor = "#14b8a6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0fdfa"
textColor = "#111827"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
